spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

# 웹에서 복사한 공연 포스터 업로드 허용 크기
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
